# src/Acme/StoreBundle/Resources/config/doctrine/Product.mongodb.yml
Acme\StoreBundle\Document\FosGroup:
    repositoryClass: Acme\StoreBundle\Repository\FosGroupRepository
    fields:
        id:
            id:  true
        name:
            type: string
        roles:
            type: string