# src/Acme/AccountBundle/Resources/config/doctrine/User.mongodb.yml
App1Bundle\Document\User:
    fields:
        id:
            id:  true
        email:
            type: string
        password:
            type: string