# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
#    token_authenticator:
#        class: UserBundle\Security\TokenAuthenticator
#        arguments: ['@lexik_jwt_authentication.jwt_encoder', '@doctrine.mongodb.entity_manager']
    admin.category:
        class: App1Bundle\Admin\CategoryAdmin
        arguments: [~, App1Bundle\Document\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: Category }
    
    admin.blog_post:
        class: App1Bundle\Admin\BlogPostAdmin
        arguments: [~, App1Bundle\Document\BlogPost, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: Blog post }
            
    app.admin.post:
        class: App1Bundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Content", label: "Post" }
        arguments:
            - ~
            - App1Bundle\Document\Post
            - App1Bundle:PostAdmin
        calls:
            - [ setTranslationDomain, [AppBundle]]
    token_authenticator:
        class: Acme\StoreBundle\Security\TokenAuthenticator
        arguments: ['@lexik_jwt_authentication.encoder.default', '@doctrine_mongodb']
#    acme.store.security.guard.jwt_token_authenticator:
#        parent: lexik_jwt_authentication.security.guard.jwt_token_authenticator
#        class: AcmeStoreBundle\Security\Guard\JWTAuthenticator
