# src/AppBundle/Resources/config/admin.yml
#services:
#       app.admin.post:
#        class: AppBundle\Admin\PostAdmin
#        tags:
#            - name: sonata.admin
#              manager_type: doctrine_mongodb
#              group: "app.admin.group.content"
#              label: "app.admin.model.post"
#              label_catalogue: "AppBundle"
#        arguments:
#            - ~
#            - AppBundle\Entity\Post
#            - ~
          
  